### ISSUE TITLE
remove Text placeholder

### ISSUE THREAD

**Issue by nagamalleshavenkategowda** [Kaier33/easy-drawing-board#4]
Is it possible to remove placeholder text in textarea when I add it to canvas?

**Comment by Kaier33** [comment]
In the latest version, as long as your browser language is not Chinese,  the textarea's placeholder is 'Type here...'.

or, you can give it a default value, like this:

```js
new EasyDrawingBoard({container: Dom, textareaPlaceholder: 'Arbitrary string...'});
```
