### ISSUE TITLE
Not working with firefox

### ISSUE THREAD

**Issue by nagamalleshavenkategowda** [Kaier33/easy-drawing-board#5]
You can check using below link in firefox
https://codepen.io/kaierchou/project/editor/AEepEK#

This issue can be fixed by using following properties
![image](https://user-images.githubusercontent.com/49677363/110429860-87cfe100-80d1-11eb-99bb-e4f30ba39b98.png)

**Comment by Kaier33** [comment]
Thank you for fixed it
